"""auto-vote

Revision ID: 656890e0a511
Revises: 51c0cfcb5748
Create Date: 2022-03-25 17:21:34.498766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '656890e0a511'
down_revision = '51c0cfcb5748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('votes')

    # ### end Alembic commands ###
