"""add phone number

Revision ID: f598678d263e
Revises: 656890e0a511
Create Date: 2022-03-25 17:25:57.434362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f598678d263e'
down_revision = '656890e0a511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('phone_number', sa.String(),nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users','phone_number')
    # ### end Alembic commands ###
